# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d91af16338624688d06ea448f11fd6d6cb767f8ea54cfcd69985a642e8160d747b0ce75d4dacd9ffe08883b96c677162cb7cb3eba1669cb1c2763b75e4bfa9

test:
  secret_key_base: 721ffabe888bf216a6f9ddfc84fb07ca9ad80cf4ba3cfe96f1444014f951a8a1962b98807d455432a7b397bc55922531ada40f899e6ffa78247c07e3e9aa55f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
